---

- name: Add floating IP to instance
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: "{{ item.floating_ip }}"
    wait: true
    timeout: 200
  loop: "{{ site_info }}"